
### Obtener todos los clientes
GET  http://localhost:8000/cliente

### Crear un nuevo cliente
POST  http://localhost:8000/cliente
Content-Type: application/json

{
  "nombre": "Luis",
  "apellido": "Salamanca",
  "email": "Salamanca@gmail.com",
  "telefono": "3159876543"
}

### Actualizar un Cliente
PUT http://localhost:8000/cliente
Content-Type: application/json

{
  "idCliente": "1",
  "nombre": "Luis",
  "apellido": "Ramirez",
  "email": "gomez@gmail.com",
  "telefono": "3159876543"
}

### Eliminar un Cliente
DELETE http://localhost:8000/cliente
Content-Type: application/json

{
  "idCliente": 1
}

### Obtener todas las mascotas
GET http://localhost:8000/mascota

### Crear una nueva mascota
POST http://localhost:8000/mascota
Content-Type: application/json

{
  "nombre": "Bruno",
  "especie": "Perro",
  "raza": "Lobo",
  "edad": 3,
  "idCliente": 2
}

### Actualizar una mascota
PUT http://localhost:8000/mascota
Content-Type: application/json

{
  "idMascota": 1,
  "nombre": "Max Jr",
  "especie": "Perro",
  "raza": "Golden Retriever",
  "edad": 4,
  "idCliente": 2
}

### Eliminar una mascota
DELETE http://localhost:8000/mascota
Content-Type: application/json

{
  "idMascota": 1
}


